### ISSUE TITLE
Pytearcat 0.0.7 seems to be unable to display mixed index case and raised index case of the Ricci tensor

### ISSUE THREAD

**Issue by weka511** [pytearcat/pytearcat#16]
Pytearcat 0.0.7 seems to be unable to display mixed index case and raised index case of the Ricci tensor and Einstein tensor. Here is a minimal example:
```python
import pytearcat as pt
t,r,theta,phi = pt.coords('t,r,theta,phi')
nu = pt.fun('nu','t,r')
lambda_ = pt.fun('lambda_','t,r')
ds = 'ds2 = exp(nu)*dt**2 - exp(lambda_)*dr**2 - r**2*(dtheta**2 + sin(theta)**2 *dphi**2)'
g = pt.metric(ds)
g.display('^,_') #This displays the expected result
g.display('^,^') #This displays the expected result
R = pt.ricci()
R.display('_,_')   #This displays the expected result
R.display('^,_')   #This displays NANs
R.display('^,^')   #This displays NANs
```

**Comment by jmsureda** [comment]
Hi Simon, thanks for providing a good example. Note that this is currently the intended behavior of pytearcat. By default, when you compute a "predefined" tensor, it will only compute the minimal index combinations needed. In this example, when you do `R = pt.ricci()`, it will only compute the ("_, _") component of the tensor to reduce computing time. If you need all other index cases you have two options:

1. Pass the argument `All=True` to the ricci function

```python
R = pt.ricci(All=True)
```
Then all the tensor components will be computed when the tensor is defined.

2. Use the `complete` method to compute the missing index combinations of a tensor

```python
R = pt.ricci()
R.complete('_,_')
```
This will compute the rest of index combinations starting from the given index (in this case "_, _" ).

I hope this helps!

**Comment by weka511** [comment]
Many thanks for your prompt reply. I'm sorry to have put you to this trouble.
