### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by plasky** [pytearcat/pytearcat#8]
Thank you for this wonderful code. I am beginning to develop some course material where I would like to use this software.

At the moment, pytearcat requires numpy==1.19.0. I was having trouble reverting back to this version of numpy, so instead changed the dependency of pytearcat such that numpy>=1.19.0. This seems to be working fine (with numpy==1.21.5), is there a reason for holding back the dependency?

Thank you,
Paul

**Comment by jmsureda** [comment]
Hi Paul,

thanks for your interest in Pytearcat. The original reason to hold the numpy version was related to the compatibility with giacpy. For newer versions of numpy, giacpy simply did not work. We will evaluate if it is worth to keep holding the numpy version just for giacpy. 

In any case, thank you again for your comment and for letting us know that it works fine with newer numpy versions.

Best,
Joaquin

**Comment by Tardelius** [comment]
> Thank you for this wonderful code. I am beginning to develop some course material where I would like to use this software.
> 
> At the moment, pytearcat requires numpy==1.19.0. I was having trouble reverting back to this version of numpy, so instead changed the dependency of pytearcat such that numpy>=1.19.0. This seems to be working fine (with numpy==1.21.5), is there a reason for holding back the dependency?
> 
> Thank you, Paul

How did you change the dependency?

**Comment by jmsureda** [comment]
This issue was solved in the [0.0.6](https://github.com/pytearcat/pytearcat/releases/tag/0.0.6) release, as in [this issue](https://github.com/pytearcat/pytearcat/issues/11#issuecomment-1646281097).
