### ISSUE TITLE
Unable to import the module in Python 3.8.10

### ISSUE THREAD

**Issue by thejusp** [pytearcat/pytearcat#9]
Unable to import the module in Python 3.8.10 after installing the module in colab. 

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-52-87dc170be2e2>](https://localhost:8080/#) in <module>
----> 1 import pytearcat as pt

8 frames

[/content/pytearcat/pytearcat/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .gr import (def_coords as coords, create_metric as metric, christoffel, riemann, ricci,
      2                  ricci_scalar as riccis, einstein, geodesic)
      3 
      4 from .tensor import (setorder as order, series, new_var as var, new_con as con, new_fun as fun, new_ten as ten,
      5                     LeviCivita as lcivita, KroneckerDelta as kdelta, D, C ,display, set_space_time as spacetime,

[/content/pytearcat/pytearcat/gr/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .metric import def_coords, create_metric
      2 from .christoffel import calculate_christoffel as christoffel
      3 from .riemann import calculate_riemann as riemann
      4 from .ricci import calculate_ricci as ricci
      5 from .ricci import calculate_ricci_scalar as ricci_scalar

[/content/pytearcat/pytearcat/gr/metric.py](https://localhost:8080/#) in <module>
      1 from itertools import product as iterprod
----> 2 from pytearcat.tensor.core import config
      3 from pytearcat.tensor.core.core import *
      4 from pytearcat.tensor.misc import new_var, reload_all
      5 from pytearcat.tensor.tensor import Tensor, tensor_series

[/content/pytearcat/pytearcat/tensor/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .misc import setorder, series, new_var, new_con, new_fun, new_ten, set_space_time, factor_pt as factor,simplify_pt as simplify,expand_pt as expand
      2 from .tensor import D, C, determinant as det
      3 from .core import display
      4 from .lcivita import LeviCivita
      5 from .kdelta import KroneckerDelta

[/content/pytearcat/pytearcat/tensor/misc.py](https://localhost:8080/#) in <module>
      5 import numpy as np
      6 from re import findall,search
----> 7 from .core import config
      8 from .core import ptseries
      9 from .core.core import get_name, simplify, factor, expand, series as Series,core_calc

[/content/pytearcat/pytearcat/tensor/core/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .display import display

[/content/pytearcat/pytearcat/tensor/core/display.py](https://localhost:8080/#) in <module>
      1 from re import findall,search
----> 2 from pytearcat.tensor.core import config
      3 from .core import get_name, latex, display_IP, Math_IP, core_calc
      4 
      5 if core_calc == "gp":

[/content/pytearcat/pytearcat/tensor/core/config.py](https://localhost:8080/#) in <module>
      1 from .greek import *
      2 
----> 3 from .core import core_calc
      4 from .fun import fun
      5 from .ptseries import *

[/content/pytearcat/pytearcat/tensor/core/core.py](https://localhost:8080/#) in <module>
     15     else:
     16 
---> 17         raise(EnvironmentError("There are missing modules:"(__missing-{'giacpy'})))
     18 
     19 

TypeError: 'str' object is not callable

**Comment by jmsureda** [comment]
Hi thejusp, we'll have a look into this issue.

**Comment by jmsureda** [comment]
Since release [0.0.7](https://github.com/pytearcat/pytearcat/releases/tag/0.0.7), Pytearcat is working correctly on Google Colab notebooks. I'm closing this issue now.
